CREATE TABLE IF NOT EXISTS "opensurveillancedb-alphav1"."defining_characteristic" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" text NOT NULL,
	CONSTRAINT "defining_characteristic_name_key" UNIQUE ("name"),
	CONSTRAINT "defining_characteristic_name_not_blank" CHECK (length(btrim(name)) > 0)
);

CREATE TABLE IF NOT EXISTS "opensurveillancedb-alphav1"."device_model_defining_characteristic" (
	"model_id" uuid NOT NULL,
	"characteristic_id" bigint NOT NULL,
	CONSTRAINT "device_model_defining_characteristic_pkey" PRIMARY KEY ("model_id", "characteristic_id"),
	CONSTRAINT "device_model_defining_characteristic_model_id_fkey"
		FOREIGN KEY ("model_id")
		REFERENCES "opensurveillancedb-alphav1"."device_model"("id")
		ON DELETE CASCADE,
	CONSTRAINT "device_model_defining_characteristic_characteristic_id_fkey"
		FOREIGN KEY ("characteristic_id")
		REFERENCES "opensurveillancedb-alphav1"."defining_characteristic"("id")
		ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "device_model_defining_characteristic_characteristic_idx"
	ON "opensurveillancedb-alphav1"."device_model_defining_characteristic" ("characteristic_id");

INSERT INTO "opensurveillancedb-alphav1"."defining_characteristic" ("name")
SELECT DISTINCT btrim(feature)
FROM "opensurveillancedb-alphav1"."device_model" dm
CROSS JOIN LATERAL unnest(dm."distinguishing_features") AS feature
WHERE length(btrim(feature)) > 0
ON CONFLICT ("name") DO NOTHING;

INSERT INTO "opensurveillancedb-alphav1"."device_model_defining_characteristic" ("model_id", "characteristic_id")
SELECT dm."id", dc."id"
FROM "opensurveillancedb-alphav1"."device_model" dm
CROSS JOIN LATERAL unnest(dm."distinguishing_features") AS feature
JOIN "opensurveillancedb-alphav1"."defining_characteristic" dc
	ON dc."name" = btrim(feature)
WHERE length(btrim(feature)) > 0
ON CONFLICT ("model_id", "characteristic_id") DO NOTHING;

ALTER TABLE "opensurveillancedb-alphav1"."device_model"
	DROP CONSTRAINT IF EXISTS "device_model_distinguishing_features_not_blank";

ALTER TABLE "opensurveillancedb-alphav1"."device_model"
	DROP COLUMN IF EXISTS "distinguishing_features";
